"""empty message

Revision ID: 5535649bb6dd
Revises: 024575c5282b
Create Date: 2021-06-23 09:25:14.489615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5535649bb6dd'
down_revision = '024575c5282b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artist', 'venue_description')
    op.drop_column('artist', 'looking_for_venues')
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('venue', 'talent_description')
    op.drop_column('venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('talent_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'seeking_talent')
    op.add_column('artist', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('venue_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
